name: Pipeline examen dangondom1

on:
  push:
    branches:
    - cambiosP2
    - testing

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Ejecutando los test
        run: |
          chmod +x gradlew
          ./gradlew test

  Publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: echo "El desarrollador dangondom1 está añadiendo una nueva versión"

      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3

      - name: Configurando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Publicando el artefacto
        run: |
          chmod +x gradlew
          ./gradlew publish

      - run: echo "El desarrollador dangondom1 ha añadido una nueva versión"

  Debug;
    runs-on:ubuntu-latest
    run: echo "${{ secrets.DESTINATARIO }}"

  Mail:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "Artefacto de dangondom1 publicado"
          body: "El artefacto generado por dangondom1 se ha publicado correctamente."
          to: ${{ secrets.DESTINATARIO }}
          from: dangondom1